logs_root_path: code/data_volume/pdc_synthetic_2/logs_proto
object_id: "rope_nonrigid_2596vert_depth_test"
train:
- "rope_nonrigid_2596vert_depth_test"
test:
- "rope_nonrigid_2596vert_depth_test_test"
