logs_root_path: code/data_volume/pdc_synthetic_2/logs_proto
object_id: "rope_902_mixed_slightvar_depth_test"
train:
- "rope_902_mixed_slightvar_depth_test"
test:
- "rope_902_mixed_slightvar_depth_test_test"
